<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_preprocess_HOOK() for book_navigation.
 */
function bcbb_book_preprocess_book_navigation(array &$variables): void {
  // Only display the list of child pages on root book page.
  if ($variables['current_depth'] > 1) {
    unset($variables['tree']);
  }

  // Display the summary in the list of child pages.
  if (!empty($variables['tree']['#items'])) {
    foreach ($variables['tree']['#items'] as $nid => &$item) {
      // Get the node in the current language.
      $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
      $book_page = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
      if ($book_page->hasTranslation($langcode)) {
        $book_page = $book_page->getTranslation($langcode);
      }

      // If there is a summary, set it as the suffix.
      $summary = $book_page->get('body')->summary ?? NULL;
      if ($summary) {
        $item['suffix'] = [
          '#type' => 'processed_text',
          '#format' => $book_page->get('body')->format,
          '#prefix' => '<div class="summary">',
          '#text' => $summary,
          '#suffix' => '</div>',
        ];
      }
    }
  }
}
